{{ config(materialized='table') }}

-- test model is generated by adapter-specific macro, 
-- because the quantile_transformer is not supported by all DBs
{{ adapter.dispatch('standard_scaler_model_macro')() }}
